### ISSUE TITLE
Request for new language: Karakalpak

### ISSUE THREAD

**Issue by karakalpaklingvo** [WeblateOrg/language-data#1053]
### Describe the problem

Karakalpak language is missing in the list of languages.

### Describe the solution you'd like

Hi! We are a karakalpak translators team and we would like to translate some projects on your site but unfortunately we didn't find karakalpak language in the list of languages. Could you add please karakalpak language and what kind of information do you need for it?

Some information about the language:

Language name: Karakalpak (native: Qaraqalpaq)
Script: Latin
Direction: ltr
ISO code: kaa
Plural forms: one, other

If something is missing, please, let me know, thanks.
Best regards,
KarakalpakLingvo

**Comment by karakalpaklingvo** [comment]
> The definition is there: https://hosted.weblate.org/languages/kaa/#information, probably the name should be adjusted...

Thank you) There is incorrect information about native speakers.

In Wiki: 583,410

https://en.wikipedia.org/wiki/Karakalpak_language

could you fix it please?

**Comment by nijel** [comment]
This information is currently extracted from CLDR.

If you have other machine-readable source of the population data with a permissible licensing, it can be integrated in https://github.com/WeblateOrg/language-data/blob/main/scripts/export-cldr-population, but this should be done in a separate issue and not cover only a single language.
