### ISSUE TITLE
missing aliases for ang, ca@valencia, gn, sa, sr and sr_latn

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/language-data#127]
Hello,

I feel like these values are missing ALIASES

* [x]    "ang@latin": "ang", (28 files)
* [x]    "ca-valencia": "ca@valencia", (316 files)
* [x]    "ca_XV": "ca@valencia", (69 files)
* [x]    "gug": "gn", (247 files)
* [x]    "sa_IN": "sa", (271 files)
* [x]    "sr@ije": "sr", (19 files)
* [x]    "sr@ijekavian": "sr", (490 files)
* [x]    "sr@ijekavianlatin": "sr_latn" (490 files)

if required, here are a list of files concerned by these values:
[error.json.txt](https://github.com/WeblateOrg/language-data/files/5508428/error.json.txt)

**Comment by nijel** [comment]
Hmm, not sure these should be aliases:

* [Ijekavian](https://en.wiktionary.org/wiki/Ijekavian) seems to be a dialect, aliasing it to Serbian seems wrong.
* [gug](https://iso639-3.sil.org/code/gug) and [gn](https://iso639-3.sil.org/code/grn) are different languages as well

I didn't yet look at others.
