### ISSUE TITLE
Stop using "Chinese (language name, script/variant name)" as the main name for languages under Sinitic language group

### ISSUE THREAD

**Issue by winstonsung** [WeblateOrg/language-data#1410]
### Describe the problem

Currently, most languages under Sinitic language group are having "Chinese (language name, script/variant name)"-style names.

However, this would be confusing as:

- We mostly only use "Chinese" to refer "Mandarin"/"Cantonese".
- Only writing "Simplified" does not indicate the difference is based on script (writing system).

For example, `gan` "Gan" (preferred solution) / "Gan Chinese" (alternative solution) / "Chinese (Gan)" (confusing option)

### Describe the solution you would like

- `cdo-Hans` "Mindong (Simplified Han script)"
- `cdo-Hant` "Mindong (Traditional Han script)"
- `cdo-Latn` "Mindong (Latin script)"
- `cpx-Hans` "Pu–Xian Min (Simplified Han script)"
- `cpx-Hant` "Pu–Xian Min (Traditional Han script)"
- `cpx-Latn` "Pu–Xian Min (Latin script)"
- `gan-Hans` "Gan (Simplified Han script)"
- `gan-Hant` "Gan (Traditional Han script)"
- `hak-Hans` "Hakka (Simplified Han script)"
- `hak-Hant` "Hakka (Traditional Han script)"
- `hak-Latn` "Hakka (Latin script)"
- `hsn` "Xiang"
- `lzh` "Literary Chinese"
- `nan-Hant` "Hokkien (Traditional Han script)"
- `nan-Latn-pehoeji` "Hokkien (Pe̍h-ōe-jī)"
- `nan-Latn-tailo` "Hokkien (Tâi-lô)"
- `wuu-Hans` "Wu (Simplified Han script)"
- `wuu-Hant` "Wu (Traditional Han script)"
- `yue-Hans` "Cantonese (Simplified Han script)"
- `yue-Hant` "Cantonese (Traditional Han script)"
- `zh-Hans` "Chinese (Traditional Han script)"
- `zh-Hans-SG` "Chinese (Traditional Han script, Singapore)"
- `zh-Hant` "Chinese (Traditional Han script)"
- `zh-Hant-HK` "Chinese (Traditional Han script, Hong Kong)"
- `zh-Latn-CN` "Chinese (Hanyu Pinyin, Mainland China)"
- `zh-Latn-TW-pinyin` "Chinese (Hanyu Pinyin, Taiwan)"
- `zh-Latn-TW-tongyong` "Chinese (Tongyong Pinyin, Taiwan)"
- `zh-Latn-TW-wadegile` "Chinese (Wade–Giles, Taiwan)"

### Describe alternatives you have considered

- `cdo-Hans` "Mindong (Simplified Han)"
- `cdo-Hant` "Mindong (Traditional Han)"
- `cdo-Latn` "Mindong (Latin)"
- `cpx-Hans` "Pu–Xian Min (Simplified Han)"
- `cpx-Hant` "Pu–Xian Min (Traditional Han)"
- `cpx-Latn` "Pu–Xian Min (Latin)"
- `gan-Hans` "Gan (Simplified Han)"
- `gan-Hant` "Gan (Traditional Han)"
- `hak-Hans` "Hakka (Simplified Han)"
- `hak-Hant` "Hakka (Traditional Han)"
- `hak-Latn` "Hakka (Latin)"
- `hsn` "Xiang"
- `lzh` "Literary Chinese"
- `nan-Hant` "Hokkien (Traditional Han)"
- `nan-Latn-pehoeji` "Hokkien (Pe̍h-ōe-jī)"
- `nan-Latn-tailo` "Hokkien (Tâi-lô)"
- `wuu-Hans` "Wu (Simplified Han)"
- `wuu-Hant` "Wu (Traditional Han)"
- `yue-Hans` "Cantonese (Simplified Han)"
- `yue-Hant` "Cantonese (Traditional Han)"
- `zh-Hans` "Chinese (Traditional Han)"
- `zh-Hans-SG` "Chinese (Traditional Han, Singapore)"
- `zh-Hant` "Chinese (Traditional Han)"
- `zh-Hant-HK` "Chinese (Traditional Han, Hong Kong)"
- `zh-Latn-CN` "Chinese (Hanyu Pinyin, Mainland China)"
- `zh-Latn-TW-pinyin` "Chinese (Hanyu Pinyin, Taiwan)"
- `zh-Latn-TW-tongyong` "Chinese (Tongyong Pinyin, Taiwan)"
- `zh-Latn-TW-wadegile` "Chinese (Wade–Giles, Taiwan)"

**Comment by winstonsung** [comment]
(push)

**Comment by nijel** [comment]
Pull requests are welcome! Master language definitions are at https://github.com/WeblateOrg/language-data/blob/main/languages.csv

**Comment by winstonsung** [comment]
> @nijel wrote:
> Pull requests are welcome! Master language definitions are at https://github.com/WeblateOrg/language-data/blob/main/languages.csv

Thanks. However, not all
```
weblate_language_data\locale\*\LC_MESSAGES\django.po
```
files were updated when using
```bash
make
```
(especially for those language tag with underscores), any ideas about the issue (or is it intended)?
