### ISSUE TITLE
Kurdish RTL problem

### ISSUE THREAD

**Issue by CrowdsourceKurdish** [WeblateOrg/language-data#153]
Hello,
RTL should not be active as the Kurdish language is written in the Latin alphabet. Strings cannot be saved as LTR, although I switched to LTR during translation.
![bug](https://user-images.githubusercontent.com/72891963/100324724-aefa1b00-2fd8-11eb-84af-cdaa836e8e66.JPG)

**Comment by jwtiyar** [comment]
> Inviting @jwtiyar and @comradekingu to this discussion as they contributed to #3
> 
> Should "Kurdish" (ku/kur) be RTL or LTR language? Right now Weblate defines it as RTL since [WeblateOrg/weblate@fa54a49](https://github.com/WeblateOrg/weblate/commit/fa54a491fa1), but due to bug (which I've just fixed in [WeblateOrg/weblate@74cb8ca](https://github.com/WeblateOrg/weblate/commit/74cb8ca0dc)) Hosted Weblate has it as LTR.

Hey nijel
Kurdish is the name of the language but kurdish has two main dialect which are Sorani(Central Kurdish) and Kurmanci(Northern Kurdish)
They both can be written in rtl and ltr
For example:
کوردی and kurdî 
And both are the same thing they can be written in ltr or rtl.
Both dialect can use English script and Arabic script for writing.
But almost 90% if iam not wrong(because iam Sorani) of kurmanci uses english script for writing and more than %95 of sorani uses Arabic script.
So as a clear view to every one in any project we suggest using english script for kurmanci and Arabic script for sorani.
I mentioned before that Kurdish should not be provided to any project because its the main language and can be written in both script, So you can't specify Kurdish is ltr or rtl because in fact it can be written in both, My suggestion is to activate the projects as central kurdish(sorani) and northern kurdish(kurmanci) not Kurdish under any circumastances. To avoid this misunderstanding.

**Comment by jwtiyar** [comment]
> Hello,
> RTL should not be active as the Kurdish language is written in the Latin alphabet. Strings cannot be saved as LTR, although I switched to LTR during translation.
> ![bug](https://user-images.githubusercontent.com/72891963/100324724-aefa1b00-2fd8-11eb-84af-cdaa836e8e66.JPG)

Dear Croudsourcekurdish
Please be carefull kurdish is written in both rtl and ltr, As it seems you are kurmanci so you should activate a project which is ltr, The kurdish could not be used anymore for just kurmanci because kurdish is not kurmanci but kurmanci is a dialect of kurdish.
Because this could make a big problem for us as sorani speakers.

**Comment by comradekingu** [comment]
So 
1 Set definition of Sorani "[ckb](https://hosted.weblate.org/languages/ckb/#information)" (arabic) to RTL (already done)
2 Set definition of  Kurmanci "[kmr](https://hosted.weblate.org/languages/kmr/#information)" (latin) to LTR (already done)

Or is it better to detect whether latin or arabic letters are used? Should the user set it as a switch in the <5% cases?

3 Remove "Kurdish" ([ku](https://hosted.weblate.org/languages/ku/#information)) locale and put projects in respective categories.
Ku is the one people use though https://hosted.weblate.org/languages/ku/#overview , whereas kmr is currently empty.
Is there anything written in Sorani in the "ku" one?

As I understand it ku is the main one, and "ckb" is specified for when it is specifically Sorani.

**Comment by jwtiyar** [comment]
> So
> 1 Set definition of Sorani "[ckb](https://hosted.weblate.org/languages/ckb/#information)" (arabic) to RTL (already done)
> 2 Set definition of Kurmanci "[kmr](https://hosted.weblate.org/languages/kmr/#information)" (latin) to LTR (already done)
> 
> Or is it better to detect whether latin or arabic letters are used? Should the user set it as a switch in the <5% cases?
> 
> 3 Remove "Kurdish" ([ku](https://hosted.weblate.org/languages/ku/#information)) locale and put projects in respective categories.
> Ku is the one people use though https://hosted.weblate.org/languages/ku/#overview , whereas kmr is currently empty.
> Is there anything written in Sorani in the "ku" one?
> 
> As I understand it ku is the main one, and "ckb" is specified for when it is specifically Sorani.
Iam saying same thing as you yes, we should not include kurdish in weblate anymore.
If the user is searching for english script or kmr should choose northern kurdish or kurmanci in otherhand if some one wanted ckb should select central kurdish or sorani.
Yes There is project used kurdish for ckb i don't know if other used or not:
https://hosted.weblate.org/projects/newpipe/strings/

**Comment by CrowdsourceKurdish** [comment]
I know that Kurdish has dialects (kurmanji, sorani, xwarin), but I requested this because only "ku" can be used for kurmanji in projects. There were already two options for sorani-central.
Unicode does not accept IOS639-3, and unicode gives this;
ku_TR
Ku_IQ

ISO693-3;
Kmr: kurmanji/Northern
Ckb: sorani/central

![2555](https://user-images.githubusercontent.com/72891963/100343211-225b5700-2ff0-11eb-85bf-44b2aa8638fd.JPG)

![Uploading lang.JPG…]()

**Comment by CrowdsourceKurdish** [comment]
Sorry, I couldn't find Kurdish (North) on the list. But now I have found it, and I think removing Kurdish (ku) from the system will resolve the confusion.

**Comment by nijel** [comment]
> I think removing Kurdish (ku) from the system will resolve the confusion.

Well first we need to decide what to do with existing translations. Preferably contact/persuade projects to use correct code for the language.... Honestly, I have no time to push this effort.

At least following exiting Kurdish translations on Hosted Weblate seem use Arabic script:

* https://hosted.weblate.org/projects/newpipe/strings/ku/
* https://hosted.weblate.org/projects/pianobooster/pianobooster/ku/
* https://hosted.weblate.org/projects/free-tube/translations/ku/

Rest seems to be Latin (or I did wrongly construct the query to detect it).

**Comment by CrowdsourceKurdish** [comment]
I looked at the projects found in Kurdish(ku), most of them are Kurdish(north) and there is a translation progress of 15-50 words.
Only 2 of them are Kurdish(central), of which only NewPipe has been translated a lot but already translated in Kurdish (central).

![1](https://user-images.githubusercontent.com/72891963/100355587-15942e80-3003-11eb-99b4-be9d8dd8a51c.JPG)

![2](https://user-images.githubusercontent.com/72891963/100355611-1c22a600-3003-11eb-9479-b0579a48c627.JPG)

**Comment by nijel** [comment]
I've taken approach to show alert to tell the projects to adjust:

![image](https://user-images.githubusercontent.com/212189/100370472-9c96d600-3006-11eb-9063-684fc56dfc32.png)

Individual contacting them would be still useful in case somebody is willing to do that.

**Comment by nijel** [comment]
In case somebody runs into this - the code is generic and could be applied to other macrolanguages as well. Unfortunately, I don't have the knowledge where it is desired and where not (for example it doesn't seem to be desired with Arabic).

**Comment by nijel** [comment]
We're discussing changing the naming of Kurdish variants; please share your feedback on https://github.com/WeblateOrg/language-data/pull/2386
