### ISSUE TITLE
ckb_IQ: new Kurdish Sorani locale

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/language-data#2]
Message from @mike-fabian

Recently a ckb_IQ locale was added to glibc:

https://sourceware.org/bugzilla/show_bug.cgi?id=9809

So maybe it is a good idea to add that language to the list of languages supported by Weblate as well.

https://en.wikipedia.org/wiki/Sorani

**Comment by nijel** [comment]
Sorani was already supported (see https://translate.fedoraproject.org/languages/ckb/#information), I've added Iraq and Iran variants.

**Comment by mike-fabian** [comment]
Thank you! I also saw that Sorani was already supported shortly after writing the request add it and wondered how I could have been so blind not to see it. Sorry!

**Comment by nijel** [comment]
We're discussing changing the naming of Kurdish variants; please share your feedback on https://github.com/WeblateOrg/language-data/pull/2386
