### ISSUE TITLE
Alias pl_PL to pl

### ISSUE THREAD

**Issue by m-aciek** [WeblateOrg/language-data#242]
**Is your feature request related to a problem? If so, please describe.**

Sometimes Polish language is coded as `pl_PL` which is legal locale code, but shouldn't be used for Polish language (`pl` should). The problem is Weblate doesn't recognise such a language, and in effect doesn't apply Polish plural rules or don't display a language name on a languages list.

**Describe the solution you'd like**

Add pl_PL as an alias of pl.

**Alternatives**

Add pl_PL as a new language, Polish (Poland). In my opinion it's not wanted.

**Screenshots**

![Zrzut ekranu 2021-01-20 o 00 52 15](https://user-images.githubusercontent.com/9288014/105108141-ead1ce00-5ab9-11eb-826e-cd1ecd49d6ac.png)

**Comment by nijel** [comment]
That should be already covered by https://github.com/WeblateOrg/language-data/blob/master/default_countries.csv unless you've disabled https://docs.weblate.org/en/latest/admin/config.html#simplify-languages
