### ISSUE TITLE
Chinese (Taiwan) missing

### ISSUE THREAD

**Issue by Kissaki** [WeblateOrg/language-data#303]
I am migrating a project away from Transifex to Weblate. Transifex has a language code `zh_TW` for `Chinese (Taiwan)`.

There seems to be no language or alias for this language code.

`zh_CN` maps to `zh_Hans` via alias. `zh_hk` maps to `zh_Hant_HK` via alias.

So I believe a new language has to be added, and with the `Hant`/`Hans` addition. But I am not sure if it is based on traditional or simplified Chinese. I tried researching a bit, but I did not come to clearly correct results.

* [Transifex Languages](https://www.transifex.com/explore/languages/)

**Comment by nijel** [comment]
No, please see https://docs.weblate.org/en/latest/faq.html#why-does-weblate-use-language-codes-such-sr-latn-or-zh-hant

**Comment by Kissaki** [comment]
Shouldn’t there be an alias for `zh_TW` then?

**Comment by nijel** [comment]
It is there:

https://github.com/WeblateOrg/language-data/blob/0c22444a63d2890979ed3fd1c59fe9ba89eb0c34/aliases.csv#L69

**Comment by return42** [comment]
@nijel sorry for my dump question, I do not have deep understanding of the aliases.csv and what it means;

Why do all map to the same `zh_Hant` / why is the country code not needed (stripped)?

https://github.com/WeblateOrg/language-data/blob/b644b831e0ec850498306298660612e1a7438064/aliases.csv#L6-L7

https://github.com/WeblateOrg/language-data/blob/b644b831e0ec850498306298660612e1a7438064/aliases.csv#L72-L75

To pick one from the obove; does it mean that there is a `zh_Hant_TW` also?

Related: https://github.com/searxng/searxng/issues/195

**Comment by nijel** [comment]
Historically, `zh_TW` was used for Traditional Chinese and `zh_CN` for Simplified Chinese. These aliases try to map these to `zh_Hant`/`zh_Hans` reasonably (including various weird codes found in the wild).

Generally, Weblate internally prefers language codes without country code for the primary country of the language (for example, is uses `cs` instead of `cs_CZ`).
