### ISSUE TITLE
Add Shavian script

### ISSUE THREAD

**Issue by trosel** [WeblateOrg/language-data#581]
### Describe the problem

The dropdown list of languages on all weblate projects i've seen do not include the Shavian script for English.

### Describe the solution you'd like

list `en-Shaw` as an option in the weblate language list so that it displays as an option in the dropdown language list on projects

### Additional context

According to the [ISO code standards](https://en.wikipedia.org/wiki/ISO_15924), languages sometimes need additional data for different scripts. For example, `sr-Cyrl` vs `sr-Latn` (Serbian in Cyrillic vs Latin scripts). 

English can be written in the [Shavian script](https://en.wikipedia.org/wiki/Shavian_alphabet) which is supported by Unicode and has the ISO code `Shaw`. Additionally, if you use country codes, it may look like `en-US-Shaw` for example.

**Comment by trosel** [comment]
@nijel Can you give me some information about your opinion on this? Why it's closed?

I believe that my request for Shavian support would also solve the issue in #248. For kazakh, you would add the additional ISO code for the script. `-Latn` or `-Cyrl`

**Comment by trosel** [comment]
@nijel should I expect to see **English (Shavian)** as an option in the dropdown options now? 

![image](https://user-images.githubusercontent.com/1299322/154814744-d364014d-e31d-487d-a2ea-7526cfa1ee2a.png)

**Comment by nijel** [comment]
It is now there: https://hosted.weblate.org/languages/en-Shaw/#information

**Comment by nijel** [comment]
Done in 6b3c12c1ade29101c81159ed0df221d996dbf732

**Comment by trosel** [comment]
@nijel thank you! but it looks like you put `English (Shavian, United Kingdom)` twice instead of `English (Shavian, United Kingdom)` and `English (Shavian, United States)` both

**Comment by nijel** [comment]
Ooops, fixed now.
