### ISSUE TITLE
Why are id, tr and many other not in LANGUAGES?

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/language-data#77]
hello,

I'm wondering why many languages are not in [language_codes](https://github.com/WeblateOrg/language-data/blob/master/weblate_language_data/language_codes.py) file while existing in [languages](https://github.com/WeblateOrg/language-data/blob/master/weblate_language_data/languages.py)?

I have the case for id, tr, etc.

I assume there is a good reason, but just can't get it.

thanks for your help!

**Comment by Jibec** [comment]
ok, I may argue it would make more sense to keep exception into translation-finder, but it have no real impact on me
I just added the "languages" file as a fallback and my [script](https://pagure.io/fedora-localization-statistics/blob/master/f/build_language_list.py#_79 ) works fine

**Comment by nijel** [comment]
> ok, I may argue it would make more sense to keep exception into translation-finder,

That's valid point. This generated file used to be part of translation-finder, but I've consolidated that to language-data and having the exceptions coded there makes little sense.
