### ISSUE TITLE
Add Saraiki language Support

### ISSUE THREAD

**Issue by mpQadir** [WeblateOrg/language-data#855]
### Describe the issue

Saraiki language is missing in the site and libreoffice. So Saraiki language be supported.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

weblate.org service

### Additional context

Saraiki language is missing in the site and libreoffice. So Saraiki language be supported.

**Comment by nijel** [comment]
Fixed in https://github.com/WeblateOrg/language-data/commit/c9a623c7f146ac02d8885c0d7ce176e423a7681a
