### ISSUE TITLE
Removed string(s) is still added as a new string in Weblate

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/language-data#955]
### Describe the issue

Removed string(s) is still added as a new string in Weblate (https://github.com/WeblateOrg/language-data/commit/bd94a96b09e83713ccc6072fc75309f137b8c883).

This string only has one target language: https://hosted.weblate.org/translate/weblate/languages/nn/?checksum=1a41cc0e345c0d21

Example:
https://hosted.weblate.org/translate/weblate/languages/en/?checksum=1a41cc0e345c0d21#history

AFAIK, I have seen this reproduced several times, but only in the [Language data](https://hosted.weblate.org/projects/weblate/languages/) component.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/translate/weblate/languages/en/?checksum=1a41cc0e345c0d21

### Screenshots

https://hosted.weblate.org/translate/weblate/languages/en/?checksum=1a41cc0e345c0d21#history
![image](https://user-images.githubusercontent.com/49396421/235305435-8df05e80-a7c7-4406-9c23-54e51179e7b9.png)
https://hosted.weblate.org/translate/weblate/languages/nn/?checksum=1a41cc0e345c0d21
![image](https://user-images.githubusercontent.com/49396421/235305828-60aee83a-a0f8-4de1-9ef3-32fd940199c1.png)

**Comment by nijel** [comment]
Looks like `nn` PO file was not updated for some reason, it got fixed in 8d32f7f7fc25f17292671de4f824856aefdaa012.
